# Generated by Django 5.2.6 on 2025-10-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0003_mission_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="mission",
            name="start_date",
            field=models.DateField(),
        ),
    ]
