# Generated by Django 5.2.6 on 2025-11-15 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0004_alter_mission_end_date_alter_mission_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="is_individual",
        ),
        migrations.AddField(
            model_name="mission",
            name="couple_registration_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="registration_close_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="registration_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="registration_fee_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="missioncategory",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[("one_day", "One Day"), ("week_long", "Week Long")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="missionjiaparticipant",
            name="coming_as_couple",
            field=models.BooleanField(default=False, help_text="Coming as a couple"),
        ),
        migrations.AddField(
            model_name="missionjiaparticipant",
            name="partner_name",
            field=models.CharField(
                blank=True,
                help_text="Partner's full name if coming as a couple",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="missions",
                to="missions.missioncategory",
            ),
        ),
        migrations.AlterField(
            model_name="missiongallery",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="galleries",
                to="missions.mission",
            ),
        ),
        migrations.AlterField(
            model_name="missionjiaparticipant",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="missions.mission",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="missions.mission",
            ),
        ),
    ]
