# Generated by Django 5.2.6 on 2025-11-20 12:53

import missions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0005_remove_mission_is_individual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="banner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=missions.models.get_missions_banner_dir
            ),
        ),
        migrations.AddField(
            model_name="missionjiaparticipant",
            name="facilitation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Facilitation amount if needs facilitation",
                max_digits=10,
                null=True,
            ),
        ),
    ]
