# Generated by Django 5.2.6 on 2025-10-26 19:18

import base.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("missions", "0004_alter_mission_end_date_alter_mission_start_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Soul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("new_convert", "New convert"),
                            ("follow_up", "Follow up"),
                        ],
                        default="new_convert",
                        max_length=50,
                    ),
                ),
                ("date_added", models.DateField()),
                ("is_personal", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=50
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("0-12", "Child (0–12 years)"),
                            ("13-17", "Young Teen (13–17 years)"),
                            ("18-24", "Young Adult (18–24 years)"),
                            ("25-39", "Adult (25–39 years)"),
                            ("40-59", "Mature Adult (40–59 years)"),
                            ("60+", "Senior (60 years and above)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="missions.location",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="missions.mission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "souls",
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
        migrations.CreateModel(
            name="ProgressUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("content", models.TextField()),
                ("update_date", models.DateField()),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="souls.soul",
                    ),
                ),
            ],
            options={
                "db_table": "soul_progress_updates",
                "ordering": ["-update_date"],
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
        migrations.AddIndex(
            model_name="soul",
            index=models.Index(
                fields=["phone_number"], name="souls_phone_n_438b27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="soul",
            unique_together={
                ("first_name", "last_name", "phone_number", "user", "mission")
            },
        ),
    ]
