# Generated by Django 5.2.6 on 2025-11-20 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0006_mission_banner_image_and_more"),
        ("souls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="soul",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="souls",
                to="missions.location",
            ),
        ),
        migrations.AlterField(
            model_name="soul",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="souls",
                to="missions.mission",
            ),
        ),
        migrations.AlterField(
            model_name="soul",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="souls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
