# Generated by Django 5.2.6 on 2025-09-24 20:52

import base.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("apple", "Apple"),
                            ("jwt", "JWT"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name", max_length=100),
                ),
                (
                    "backend_class",
                    models.CharField(
                        help_text="Python path to backend class", max_length=200
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Provider-specific configuration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True,
                        help_text="Allow new user registration via this provider",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Provider priority (higher = preferred)"
                    ),
                ),
            ],
            options={
                "db_table": "auth_providers",
                "ordering": ["-priority", "name"],
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "permissions",
                    models.JSONField(
                        default=list, help_text="List of permission strings"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the role"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "preferred_username",
                    models.CharField(
                        blank=True,
                        help_text="User's preferred display/friendly name (not used for authentication)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=users.models.get_user_photos_dir,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="users.role"
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
        migrations.CreateModel(
            name="UserAuthProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "provider_user_id",
                    models.CharField(
                        help_text="User ID from the provider", max_length=200
                    ),
                ),
                (
                    "provider_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email from provider (may differ from user.email)",
                        max_length=254,
                    ),
                ),
                (
                    "provider_data",
                    models.JSONField(
                        default=dict, help_text="Additional data from provider"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary authentication method for this user",
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this provider was used for auth",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_auth_providers",
                        to="users.authprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_auth_providers",
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="userauthprovider",
            index=models.Index(
                fields=["user", "provider"], name="user_auth_p_user_id_2324dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userauthprovider",
            index=models.Index(
                fields=["provider_user_id"], name="user_auth_p_provide_04a5e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userauthprovider",
            index=models.Index(
                fields=["is_primary"], name="user_auth_p_is_prim_043f8a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userauthprovider",
            unique_together={("provider", "provider_user_id")},
        ),
    ]
