# Generated by Django 5.2.6 on 2025-09-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
