ALL_PERMISSIONS = {
    "view_user",
    "list_users",
    "add_user",
    "update_user",
    "delete_user",
    "view_role",
    "list_roles",
    "add_role",
    "update_role",
    "delete_role",
    "create_location",
    "view_location",
    "list_locations",
    "update_location",
    "delete_location",
    "create_mission",
    "view_mission",
    "list_missions",
    "update_mission",
    "delete_mission",
    "create_mission_category",
    "list_mission_categories",
    "view_mission_category",
    "update_mission_category",
    "delete_mission_category",
    "create_mission_report",
    "view_mission_report",
    "list_mission_reports",
    "update_mission_report",
    "delete_mission_report",
    "create_soul",
    "list_souls",
    "view_soul",
    "update_soul",
    "delete_soul",
    "create_miracle",
    "list_miracles",
    "view_miracle",
    "update_miracle",
    "delete_miracle",
    "create_testimony",
    "list_testimonies",
    "view_testimony",
    "update_testimony",
    "delete_testimony",
    "create_photo_gallery",
    "list_photo_galleries",
    "view_photo_gallery",
    "update_photo_gallery",
    "delete_photo_gallery",
    "create_progress_update",
    "view_progress_update",
    "list_progress_updates",
    "update_progress_update",
    "delete_progress_update",
    "view_auditlog",
    "list_auditlogs",
    "view_missioner_stats",
    "view_admin_stats",
    "list_permissions",
}

# Permission templates for different roles

MISSIONER_PERMISSIONS = {
    "view_location",
    "list_locations",
    "list_missions",
    "view_mission",
    "view_mission_category",
    "list_mission_categories",
    "view_mission_report",
    "view_user",
    "update_user",  # For updating own profile
    "view_role",
    "create_soul",
    "update_soul",
    "view_soul",
    "list_souls",  # TODO: Specific to own souls only
    "list_miracles",
    "create_miracle",
    "view_miracle",
    "create_testimony",
    "list_testimonies",
    "view_testimony",
    "view_photo_gallery",
    "list_photo_galleries",
    "create_progress_update",
    "list_progress_updates",  # TODO: Specific to own progress updates only
    "update_progress_update",
    "view_progress_update",
    "view_missioner_stats",
}

STAFF_PERMISSIONS = MISSIONER_PERMISSIONS | {
    "create_location",
    "update_location",
    "create_mission",
    "update_mission",
    "create_mission_category",
    "update_mission_category",
    "create_mission_report",
    "update_mission_report",
    "delete_mission_report",
    "update_soul",
    "update_miracle",
    "delete_miracle",
    "update_testimony",
    "delete_testimony",
    "create_photo_gallery",
    "update_photo_gallery",
    "delete_photo_gallery",
    "update_progress_update",
}

ADMIN_PERMISSIONS = STAFF_PERMISSIONS | {
    "view_user",
    "list_users"
    "add_user",
    "update_user",
    "delete_user",
    "view_role",
    "add_role",
    "update_role",
    "delete_role",
    "view_auditlog",
    "delete_soul",
    "delete_progress_update",
    "delete_mission",
    "delete_mission_category",
    "delete_location",
    "view_admin_stats",
    "view_missioner_stats",
    "view_auditlog",
    "list_permissions"
}

EXEC_PERMISSIONS = {
    "view_user",
    "list_users",
    "view_role",
    "list_roles",
    "view_location",
    "list_locations",
    "view_mission",
    "list_missions",
    "view_mission_category",
    "list_mission_categories",
    "view_mission_report",
    "list_mission_reports",
    "view_soul",
    "list_souls",
    "view_miracle",
    "list_miracles",
    "view_testimony",
    "list_testimonies",
    "view_photo_gallery",
    "list_photo_galleries",
    "view_progress_update",
    "list_progress_updates",
    "view_auditlog",
    "list_auditlogs",
    "view_missioner_stats",
    "view_exec_dashboard",
}

SUPERUSER_PERMISSIONS = ALL_PERMISSIONS