# Generated by Django 5.2.6 on 2025-12-07 14:26

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("creation", "Creation"),
                            ("modification", "Modification"),
                            ("deletion", "Deletion"),
                            ("reports", "Reports"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action_category", models.CharField(max_length=100)),
                ("action_description", models.CharField(max_length=300)),
                ("is_successful", models.BooleanField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("flag_suspicious", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action_category"], name="audit_logs_action__e82efb_idx"
                    ),
                    models.Index(
                        fields=["is_successful"], name="audit_logs_is_succ_94f710_idx"
                    ),
                    models.Index(
                        fields=["flag_suspicious"], name="audit_logs_flag_su_1907e6_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="audit_logs_ip_addr_919cb4_idx"
                    ),
                ],
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
    ]
