# Generated by Django 5.2.6 on 2025-11-05 22:59

import base.models
import django.db.models.deletion
import testimonies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("missions", "0004_alter_mission_end_date_alter_mission_start_date"),
        ("souls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Miracle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(help_text="Title of the miracle", max_length=255),
                ),
                ("content", models.TextField(help_text="Content of the miracle")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo associated with the miracle",
                        null=True,
                        upload_to=testimonies.models.get_testimonies_dir,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        help_text="The mission associated with this miracle",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miracles",
                        to="missions.mission",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        blank=True,
                        help_text="The soul associated with this miracle",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miracles",
                        to="souls.soul",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who submitted the miracle",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="miracles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Miracle",
                "verbose_name_plural": "Miracles",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the testimony", max_length=255
                    ),
                ),
                ("content", models.TextField(help_text="Content of the testimony")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo associated with the testimony",
                        null=True,
                        upload_to=testimonies.models.get_testimonies_dir,
                    ),
                ),
                (
                    "is_selected",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the testimony has been approved for publication",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        help_text="The mission associated with this testimony",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonies",
                        to="missions.mission",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        blank=True,
                        help_text="The soul associated with this testimony",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonies",
                        to="souls.soul",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who submitted the testimony",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimony",
                "verbose_name_plural": "Testimonies",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
    ]
