# Generated by Django 5.2.6 on 2025-11-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="miracle",
            name="is_selected",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the miracle has been selected",
            ),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="is_selected",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the testimony has been selected for publication",
            ),
        ),
    ]
