name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  #  TODO: Add ci segment for tests before deployment
  deploy:
    name: Deploy GIK Missions Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          cd ${{ secrets.PROJECT_PATH }}
          echo "Pulling latest code..."
          git fetch --all
          git reset --hard origin/main
          echo "Building and restarting containers..."
          docker compose down
          docker compose up -d --build
          docker system prune -f
          echo "Deployment complete!"
          EOF
